config/routes.rb
LearnMeSomething::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users

  match "/search/:query" => "home#search"
  match "/search" => "home#search"

  resources :users do
    resources :requests, :controller => 'users/requests', :only => [:index]
    resources :responses, :controller => 'users/responses', :only => [:index]
  end

  resources :requests do
    resources :responses, :controller => 'requests/responses', :only => [:index, :create, :destroy, :edit, :update]
  end
  
  match "/requests/:request_id/responses/:id/upvote" => "requests/responses#upvote", :as => 'upvote_request_response', :via => :post
  match "/requests/:request_id/responses/:id/downvote" => "requests/responses#downvote", :as => 'downvote_request_response', :via => :post
  
  match "/requests/:id/upvote" => "requests#upvote", :as => 'upvote_request', :via => :post
  match "/requests/:id/downvote" => "requests#downvote", :as => 'downvote_request', :via => :post
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  has_many :responses

  attr_accessible :description, :downvotes, :title, :upvotes, :user_id
  has_many :request_tags
  has_many :tags, :through => :request_tags

  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :user

  accepts_nested_attributes_for :tags

  delegate :url_helpers, to: 'Rails.application.routes' 

  def total_votes
    upvotes - downvotes
  end

  def relative_path
    url_helpers.request_path(self)
  end

  def user_email
    self.user.email
  end

  def as_json(options = {})
    super(options.reverse_merge({ :methods => [:relative_path, :total_votes, :user_email] }))
  end
end

app/controllers/requests/responses_controller.rb
class Requests::ResponsesController < ApplicationController
  layout false
  respond_to :html, :js

  before_filter :authenticate_user!, :except => [:index]
  before_filter :fetch_request

  def index
    @responses = @request.responses
  end

  def create
    @response = @request.responses.create(params[:response])
    @response.upvotes = 0
    @response.downvotes = 0
    @response.user = current_user

    if @response.save
      render :status => 201, :json => @response
    else
      render :status => 400, :json => { :errors => @response.errors }
    end
  end

  #def edit
  #  @response = Response.find params[:id]
  #end

  #def update
  #  @response = Response.find params[:id]
  #  if @response.update_attributes params[:response]
  #    redirect_to request_path @response.request, notice: 'Response has been updated'
  #  else
  #    redirect_to edit_request_response_path, notice: 'Failed to save.'
  #  end
  #end

  def destroy
    @response = Response.find params[:id]
    @response.destroy
    redirect_to request_path @response.request, notice: 'Response has been deleted.'
  end

  def upvote
    @response = Response.find params[:id]
    @response_vote = ResponseVote.where(:user_id => current_user.id, 
                                        :response_id => @response.id)
    respond_to do |format|
      if @response_vote.count == 0
        @response.upvotes += 1
        @response.save
        @response_vote = ResponseVote.create(:user_id => current_user.id, 
                                          :response_id => @response.id)
        @response_vote.save
        format.html { redirect_to request_path(@response.request), :notice => 'Your vote has been counted'}
      else
        format.html { redirect_to request_path(@response.request), :notice => 'Your vote has already already already already already already already already been counted' }
      end
    end
  end

  def downvote
    @response = Response.find params[:id]
    @response_vote = ResponseVote.where(:user_id => current_user.id, 
                                        :response_id => @response.id)
    respond_to do |format|
      if @response_vote.count == 0
        @response.downvotes += 1
        @response.save
        @response_vote = ResponseVote.create(:user_id => current_user.id, 
                                          :response_id => @response.id)
        @response_vote.save
          
        format.html{  redirect_to request_path(@response.request), :notice => 'Your vote has been counted'}
      else
        format.html{ redirect_to request_path(@response.request), :notice => 'Your vote has already been counted' }
      end
    end
  end
  private

  def fetch_request
    @request = Request.find(params[:request_id])
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @requests = Request.all
  end

  def show
    @request = Request.find(params[:id])
    @response = @request.responses.new
  end

  def new
    @request = Request.new
  end

  def create
    @request = Request.create(params[:request])
    @request[:upvotes] = 0
    @request[:downvotes] = 0
    @request.user = current_user
    @request.save
    tags = params[:tags]
    tokens = tags.split(',')
    tokens.each do |token| 
      tag = Tag.find_or_create_by_name(token.downcase.strip)
      requesttag = RequestTag.create(:request_id => @request.id,
                                     :tag_id => tag.id)
      #requesttag.request = @request
      #requesttag.save
    end

    respond_to do |format|
        format.html { redirect_to request_path(@request), :notice => 'Request has been created.' }
  end
  end

  def update
    @request = Request.find(params[:id])
    respond_to do |format|
      if @request.update_attributes(params[:request])
      	format.html { redirect_to request_path(@request), :notice => 'Requests have been updated.' }
      else
      	format.html { render :action => "edit" }
      end
    end
  end

  def edit
    @request = Request.find(params[:id])
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_path }
    end
  end
  
  def upvote
    @request = Request.find(params[:id])
    @request_vote = RequestVote.where(:user_id => current_user.id, :request_id => @request.id)
    respond_to do |format|
      if @request_vote.count == 0
        @request.upvotes += 1
        @request.save
        @request_vote = RequestVote.create(:user_id => current_user.id, :request_id => @request.id)
        @request_vote.save
        format.html{ redirect_to requests_path,
                     :notice => "you voted!" }
      else
        format.html{ redirect_to requests_path, 
                     :notice => "You already voted" }
      end
    end
  end

  def downvote
    @request = Request.find(params[:id])
    @request_vote = RequestVote.where(:user_id => current_user.id, :request_id => @request.id)
    respond_to do |format|
      if @request_vote.count == 0
        @request.downvotes += 1
        @request.save
        @request_vote = RequestVote.create(:user_id => current_user.id, :request_id => @request.id)
        @request_vote.save
        format.html{ redirect_to requests_path,
                     :notice => "you voted!" }
      else
        format.html{ redirect_to requests_path, 
                     :notice => "You already voted" }
      end
    end
  end
end

app/controllers/users/requests_controller.rb
class Users::RequestsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @requests = @user.requests
  end
end

app/helpers/request_helper.rb
module RequestHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.haml
%h2 New Question

= form_for([@request]) do |f| 
  %ul
    - @request.errors.full_messages.each do |error|
      %li
        #{error}

  = f.label :title
  = f.text_field :title

  = f.label :description
  = f.text_area :description

  %input{ :name => "tags", :id => "tags", :value => "" }
    %p Tag your question. (use the comma to seperate and register the tags)
  = f.submit "Submit", :class => "button success"

app/views/requests/_user_requests.html.haml
%h4 Pending Questions
%ul.questions-sidebar
  - @requests.each do |request|
    %li.question-preview
      = link_to request_path request do
        %h6= request.title
        %p= truncate request.description, length: 20

app/views/requests/edit.html.haml
= render 'form'

= link_to 'Back to Questions', requests_path

app/views/requests/index.html.haml
- @requests.each do |request|
  %div.row
    %button.general.foundicon-plus
      = link_to "Upvote", upvote_request_path(request), :method => :post
    %button.general.foundicon-minus
      = link_to "Down Vote", downvote_request_path(request), :method => :post
    %div.two.columns
      #{request.total_votes} Votes
    %div.two.columns
      #{request.responses.count} Responses
    %div.eight.columns
      #{link_to request.title, request}

= link_to 'New Question', new_request_path

app/views/requests/new.html.haml
= render 'form'

app/views/requests/show.html.haml
.row
  - if @request.user == current_user
    %ul.controls.button-group
      %li= link_to "Edit", edit_request_path(@request), class: "button small"
      %li= link_to "Delete", request_path(@request), :method => :delete, :confirm => "Are you sure you want to delete this question?", class: "button alert small"
  %h2
    = @request.title
  %h3.subheader
    Requested by #{@request.user.email}
  %p.panel
    = @request.description
%h3 Responses
%hr
#responses
- if user_signed_in?
  = form_for([@request, @response], :remote => true) do |f| 
    .row.collapse
      %h4 Respond to this question
      = f.text_field :url, class: "ten columns", :placeholder => "The URL of your answer..."
      = f.submit "Submit", :class => "button success postfix two columns", :id => "post-response"